os: osx
language: node_js
node_js:
- '7'
branches:
  only:
    - master
script:
- npm run build
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  local_dir: ${TRAVIS_BUILD_DIR}/styleguide
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
